language: java
sudo: false
addons:
    sonarcloud:
        organization: "bentobox-world"

jdk:
    - openjdk8
    - openjdk11
    
matrix:
  allow_failures:
    - jdk: openjdk11
        
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
    - export JAVA_HOME=$HOME/openjdk11
    - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME
    - mvn sonar:sonar -Dsonar.projectKey=BentoBoxWorld_BentoBox

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'
