name: BSkyBlock
main: us.tastybento.bskyblock.BSkyBlock
version: ${version}

authors: [tastybento, Poslovitch]

depend: [Vault]
softdepend: [Herochat, DeluxeChat, PlaceholderAPI, MVdWPlaceholderAPI]

load: startup
loadbefore: [Multiverse-Core]

commands:
    island:
        description: Main player command
        aliases: [is]
        usage:  |
             /island help
    bsadmin:
        description: Admin commands
        usage:  |
            /bsadmin help
    bsc:
        description: Game challenges
        aliases: [c, challenge, bschallenge, challenges]
        usage:  |  
            /challenge