name: BentoBox
main: world.bentobox.bbox.BentoBox
version: ${version}
api-version: 1.13

authors: [tastybento, Poslovitch]

softdepend: [PlaceholderAPI, MVdWPlaceholderAPI]

load: startup
loadbefore: [Multiverse-Core]
