name: BSkyBlock
main: us.tastybento.bskyblock.BSkyBlock
version: ${version}

authors: [Tastybento, Poslovitch]

depend: [Vault]
softdepend: [Herochat, DeluxeChat, PlaceholderAPI, MVdWPlaceholderAPI]

load: startup
loadbefore: [Multiverse-Core]

commands:
    island:
        description: Main player command
        aliases: [is]
        usage:  |
             /island help
    asadmin:
        description: Admin commands
        usage:  |
            /asadmin
    asc:
        description: Game challenges
        aliases: [c, challenge, aschallenge, challenges]
        usage:  |  
            /challenge