name: BSkyBlock
main: us.tastybento.askyblock.BSkyBlock
version: ${version}

authors: [Tastybento, Poslovitch]

depend: [Vault]
softdepend: [Herochat, DeluxeChat, PlaceholderAPI, MVdWPlaceholderAPI]

load: startup
loadbefore: [Multiverse-Core]