version: 2
jobs:
  build:
    
    working_directory: ~/circleci-bskyblock

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: circleci-bskyblock-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn clean
      - run: mvn package
      - run: mvn install
            
      - store_artifacts:
          path: target/bskyblock-alpha-0.0.1.jar
